version: '3.9'

services:

    swag:
        image: lscr.io/linuxserver/swag:latest
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - URL=pomee.hu
            - VALIDATION=dns
            - SUBDOMAINS=www, jellyseerr, generate, authentik, auth #optional
            - CERTPROVIDER=zerossl #optional
            - DNSPLUGIN=cloudflare #optional
            - PROPAGATION=60 #optional
            - EMAIL=pomee4@protonmail.com #optional
            - ONLY_SUBDOMAINS=false #optional
            - EXTRA_DOMAINS= #optional
            - STAGING=false #optional
            - DOCKER_MODS=linuxserver/mods:swag-dashboard
        volumes:
            - /d/Docker/Swag/config:/config
        ports:
            - 443:443
            - 80:80 #optional
            - 81:81
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - AUTO_UPDATE=true #optional
            - RUN_OPTS= #optional
        volumes:
            - /d/Docker/Jackett/config:/config
            - /d/data/torrents:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
        volumes:
            - /d/Docker/Jellyfin/config:/config
            - /d/Docker/Jellyfin/cache:/cache
            - /d/data/media/tv:/data/tvshows
            - /d/data/media/movies:/data/movies
        ports:
            - 8096:8096
            - 8920:8920 #optional
            - 7359:7359/udp #optional
            - 1900:1900/udp #optional
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities: [gpu]
        restart: unless-stopped
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Budapest
        ports:
            - 5055:5055
        volumes:
            - /d/Docker/Jellyseerr/config:/app/config
        restart: unless-stopped
    radarr:
        image: cr.hotio.dev/hotio/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
        volumes:
            - /d/Docker/Radarr/config:/config
            - /d/data:/data
            - /d/data/torrents:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    sonarr:
        image: cr.hotio.dev/hotio/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - UMASK=002
        volumes:
            - /d/Docker/Sonarr/config:/config
            - /d/data:/data
            - /d/data/torrents:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
    homarr:
        container_name: homarr
        image: ghcr.io/ajnart/homarr:dev
        restart: unless-stopped
        volumes:
            - /d/Docker/Homarr/config:/app/data/configs
            - /d/Docker/Homarr/icons:/app/public/icons
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 7575:7575
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - UMASK=002
            - EDIT_MODE_PASSWORD=H7KyRTFBKXZ4Eq
    jfa-go:
        restart: unless-stopped    
        container_name: jfa-go
        ports:
            - '8056:8056'
            - '8057:8057'
        volumes:
            - /d/Docker/jfa-go/config:/data
            - /d/Docker/Jellyfin/config:/jf'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
            - UMASK=002            
        image: hrfee/jfa-go:latest
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Budapest
        volumes:
            - /d/Docker/Bazarr/config:/config
            - /d/data/media/movies:/movies #optional
            - /d/data/media/tv:/tv #optional
        ports:
            - 6767:6767
        restart: unless-stopped
